# Generated by Django 2.0.6 on 2018-06-20 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.IntegerField(default=0)),
                ('frequency', models.FloatField(default=0)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='data.Speech')),
            ],
            options={
                'verbose_name': 'Speech Token',
                'verbose_name_plural': 'Speech Tokens',
                'ordering': ['occurrences'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=255)),
                ('bigram', models.BooleanField(default=False)),
                ('_originals', models.TextField(default='{}')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['stem'],
            },
        ),
        migrations.AddField(
            model_name='speechtoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='nlp.Token'),
        ),
    ]
