# Generated by Django 2.0.6 on 2018-06-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('token', 'Token'), ('author', 'Author'), ('manifestation', 'Manifestation')], max_length=20)),
                ('algorithm', models.CharField(choices=[('unigram_bow', 'Unigram Bag of Words'), ('bigram_bow', 'Bigram Bag of Words')], max_length=100)),
                ('stem', models.CharField(blank=True, max_length=255, null=True)),
                ('author_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis',
                'verbose_name_plural': 'Analyses',
            },
        ),
        migrations.CreateModel(
            name='PreProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PreProcessing',
                'verbose_name_plural': 'PreProcessings',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SpeechToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.IntegerField(default=0)),
                ('frequency', models.FloatField(default=0)),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='data.Speech')),
            ],
            options={
                'verbose_name': 'Speech Token',
                'verbose_name_plural': 'Speech Tokens',
                'ordering': ['occurrences'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(max_length=255, unique=True)),
                ('ngrams', models.IntegerField(default=1)),
                ('_originals', models.TextField(default='{}')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['stem'],
            },
        ),
        migrations.AddField(
            model_name='speechtoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='nlp.Token'),
        ),
    ]
