# Generated by Django 2.0.6 on 2018-08-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechtoken',
            name='use_indexes',
            field=models.BooleanField(default=False),
        ),
    ]
