# Generated by Django 2.0.6 on 2018-06-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='bigram',
        ),
        migrations.AddField(
            model_name='token',
            name='ngrams',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='token',
            name='stem',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
