# Generated by Django 2.0.6 on 2018-08-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0002_speechtoken_use_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='use_indexes',
            field=models.BooleanField(default=False),
        ),
    ]
