# Generated by Django 2.1.1 on 2018-11-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0003_analysis_use_indexes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreProcessing',
        ),
        migrations.RemoveField(
            model_name='speechtoken',
            name='speech',
        ),
        migrations.RemoveField(
            model_name='speechtoken',
            name='token',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='algorithm',
            field=models.CharField(choices=[('multigram_bow_with_unigram', 'Multigrams Bag of Words with unigrams'), ('multigram_bow_without_unigram', 'Multigrams Bag of Words without unigrams'), ('naive_bayes', 'Naive naive_bayes')], max_length=100),
        ),
        migrations.DeleteModel(
            name='SpeechToken',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
