# Generated by Django 2.1.1 on 2018-11-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0004_auto_20181101_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='use_indexes',
        ),
    ]
