# Generated by Django 2.1.7 on 2019-03-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0006_auto_20181108_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='phase',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
