# Generated by Django 2.1.7 on 2019-03-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp', '0007_analysis_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='gender',
            field=models.CharField(default='TODOS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='party',
            field=models.CharField(default='TODOS', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='state',
            field=models.CharField(default='TODOS', max_length=100),
            preserve_default=False,
        ),
    ]
