# Generated by Django 2.0.6 on 2018-06-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_channel', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('original', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Speech',
                'verbose_name_plural': 'Speeches',
                'ordering': ['date', 'time'],
            },
        ),
    ]
