# Generated by Django 2.0.6 on 2018-06-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='pre_processed',
            field=models.BooleanField(default=False),
        ),
    ]
