# Generated by Django 2.1.7 on 2019-03-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_speech_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Speech Theme',
                'verbose_name_plural': 'Speech Themes',
            },
        ),
        migrations.CreateModel(
            name='StemToken',
            fields=[
                ('stem', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('original', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='speech',
            name='id_in_channel',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='original',
        ),
        migrations.AddField(
            model_name='author',
            name='author_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='party',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='day_order_phase',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='identifier',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='phase',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='tokens',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='speeches', to='data.SpeechTheme'),
        ),
    ]
